### ISSUE TITLE
Subscriptions V1 embedded admin UI not working

### ISSUE THREAD

**Issue by tc-amorevino** [bold-commerce/bold-subscriptions-js#25]
Hi all,

not sure where to post this. I am thinking this might be the most reasonable place.

The embedded UI of our subscriptions V1 app has stopped working, which makes the management of individual customer subscriptions impossible.

We are seeing the following error:

![image](https://user-images.githubusercontent.com/39130169/231163540-1292b8bc-aea6-4940-97a1-6ce86f91279c.png)

Given that the UI has only recently stopped working and that a new version of app-bridge has [been published 7 days ago](https://www.npmjs.com/package/@shopify/app-bridge), I believe that the error has been caused by an automated version bump.

Is this something you guys could look into?

I know a v2 of bold subscriptions is out, we just haven't had the time to make the necessary changes for migration. The v1 has been working great so far.

cc @game-of-morgan

**Comment by njewsbury-bold** [comment]
Hey @tc-amorevino 

We recently updated our app bridge resources to 3.7.5 as you've noticed due to an issue on Shopify's side regarding their switch to a new "unified admin domain" where our original version of 2.0.3 was no longer functioning. This new version of app bridge bundles utils & "core" together, and the missing `app-bridge-utils` is expected until we remove the no longer required asset. 

With regards to the admin no longer loading correctly this is an issue with how app bridge seems to be handling the transition back to the embedded context  that the app sits in. We are actively working with Shopify to help them troubleshoot this issue. This issue popped up last week, and Shopify was able to resolve it Thursday, but something changed on their end between then and now.

This issue only seems to be impacting stores that Shopify hasn't migrated to the new unified domain. However we have determined a "workaround" to allow you to get into the app (as a temporary measure until Shopify can resolve this)

```
There is a method to skip the app bridge "login" flow by just navigating directly to the app URL:
The pattern for the app admin is
{storename}.myshopify.com/admin/apps/5a3cb5ac82a21b14f0e3fa026a88eb29/s/{storename}/home

If your store name is "nathan-test" then the URL would be 
nathan-test.myshopify.com/admin/apps/5a3cb5ac82a21b14f0e3fa026a88eb29/s/nathan-test/home
```

You can follow along with any other status updates we receive at https://status.boldcommerce.com/

Thanks for reaching out! Hopefully that workaround can help you out in the mean time. Once the issue is resolved, we will update the status page as well.

Have a great rest of your day!

**Comment by tc-amorevino** [comment]
@njewsbury-bold Thank you for the quick reply!

I can confirm that the described solution works.

Thank you!

**Comment by njewsbury-bold** [comment]
@tc-amorevino  Just wanted to ping you again - we've worked with Shopify to determine the issue and have downgraded our app bridge to 2.2.0 and that seems to have resolved the issue for both of these types of "admin domains".
So you shouldn't need that workaround anymore.
